version: "3"
services:
  social-poster_qa:
    env_file:
      - .qa.env
    container_name: social-poster_qa
    restart: always
    build: .
    ports:
      - "127.0.0.1:3000:3000"
  #   depends_on:
  #     - social-poster_redis
  #
  # social-poster_production:
  #   env_file:
  #     - .production.env
  #   container_name: social-poster_qa
  #   restart: always
  #   build: ./app
  #   ports:
  #     - "127.0.0.1:3032:3002"
  #   depends_on:
  #     - social-poster_redis
  #
  # social-poster_redis:
  #   container_name: "social-poster_redis"
  #   image: redis:latest
  #   restart: always
  #   # ports:
  #   #   - "16379:6379"
